# Generated by Django 2.2.5 on 2019-09-28 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lime', '0003_auto_20190925_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('url', models.URLField()),
                ('q', models.CharField(max_length=10, verbose_name='keywords')),
                ('icon', models.ImageField(blank=True, upload_to='search/')),
            ],
            options={
                'verbose_name': 'serach',
                'verbose_name_plural': 'serach',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['category', 'id'], 'verbose_name': 'bookmark', 'verbose_name_plural': 'bookmarks'},
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coco', to='lime.Category'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='ico',
            field=models.ImageField(blank=True, upload_to='user/b%Y/'),
        ),
    ]
